### ISSUE TITLE
Example dashboard 

### ISSUE THREAD

**Issue by idanl21** [aiven/prometheus-exporter-plugin-for-opensearch#98] opened 2022-09-06 13:32 UTC
Hey Aiven, your exporter is great!
I just wanted to ask if you have a default dashboard that I can use with it?

**Comment by lukas-vlcek** [comment] 2022-12-01 19:18
Closing as a duplicate of #12 
Please see that ticket for the latest update.

**Closed by lukas-vlcek** 2022-12-01 19:18 UTC
Labels: mixin
